print("Getting to know you!")
myname = input("What's your name?: ")
food = input("What's your favorite food?: ")
Music = input("What's your favorite music?: ")
place = input("Where do you live?: ")
print()
print("You are")
print(myname)  
print("You're probably hungry for")
print(food)
print("and you're definitely getting your groove on to")
print(Music)
print("living in the amazing")
print(place)